
theme = "PaperMod"
baseurl = "https://[yourgithubname].github.io"
 languageCode = "zh-tw" 
title = "Whatever you want" 
buildDrafts = false 

[[menu.main]]
 
identifier = "tags"
 
name = "tags"
 
url = "/tags/"
 
weight = 10

[[menu.main]]
 
identifier = "categories"
 
name = "Categories"
 
url = "/categories/"
 
weight = 20

[[menu.main]]
 
identifier = "archives"
 
name = "Archives"
 
url = "/archives/"
 
weight = 30

[params.profileMode]
enabled = true
title = "start"
subtitle = "welcomeeeeeee"
imageUrl = "img/name.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "Ting yu"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"
 
[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.socialIcons]]
name = "github"
url = "your github profile url"
#...more

[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結
 
[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視
